### PR TITLE
Remove ALNWFL after merger into SEZF BMLT

### PR DESCRIPTION
**Pull request by jbraswell**

### CODE REVIEW

**Comment by radius314** [comment]
👍

**Comment by radius314** [comment]
@LittleGreenViper how do we get this deployed?

**Comment by LittleGreenViper** [comment]
@radius314 This is done.

**Comment by radius314** [comment]
Thank you!

**Comment by LittleGreenViper** [comment]
No, thank YOU!
Hittin' the sack, now...

**Pull request merged**
