### PR TITLE
adding kansas city metro

### PR DESCRIPTION
**Pull request by radius314**

### CODE REVIEW

**Comment by LittleGreenViper** [comment]
Before integrating this, I want to reach out to them. This is the same vintage as Denmark, which won't work with Sandwich (I don't know about Tomato). It's entirely possible that this is a "research root" that has been allowed to go fallow (always a bad idea, but we addicts have a long, proud history of bad ideas).

**Comment by radius314** [comment]
I believe it’s a legit root.

**Comment by LittleGreenViper** [comment]
It is. I contacted them.

They will upgrade this weekend, so I'll integrate after they do so. It won't work in Sandwich or Tomato until they update.

If you guys can deal with older roots, I could add both KC and Denmark, but they are old, and I have no idea if Denmark will be updating (If you visit their site, you will see they reference the last conference cycle, so I think they don't have any active Webservant).

	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Comment by radius314** [comment]
Yup. I saw your mail.

**Comment by LittleGreenViper** [comment]
They still haven't updated.

Do you want to wait, or do you think you can deal with 2.6.26? Denmark is the same version.

**Comment by radius314** [comment]
Denmark or Germany?

**Comment by LittleGreenViper** [comment]
Germany (The German-Speaking Region) is quite up to date.

Denmark is the one that seems to have run out of Trusted Servants to take care of their server. Hope things are OK. In the meantime, they have an old Root Server.

**Comment by radius314** [comment]
What’s the URL for the Denmark root?

**Comment by LittleGreenViper** [comment]
http://nadanmark.dk/fixed_bmlt_root/main_server/

**Comment by radius314** [comment]
@LittleGreenViper asked @jbraswell to run a test.  What was the reason why Denmark was removed?  What's the symptoms?

**Comment by LittleGreenViper** [comment]
You asked for it to be removed.

I believe it was because it does not respond with a coverage area.

**Comment by jbraswell** [comment]
KC Metro seems to import into tomato without any issues.

**Comment by LittleGreenViper** [comment]
Denmark is the same version.

**Comment by jbraswell** [comment]
The KC Metro server does duplicate the Heartland Area. It seems to be both on the Iowa server and the KC Metro server.

**Comment by jbraswell** [comment]
Actually the meetings in the two "heartland areas" aren't the same at all, so I'm guessing they're totally different areas. IMO we should add KC Metro.

I'm running a quick test on Denmark right now.

**Comment by jbraswell** [comment]
Denmark looks good, too. Unless there's something else that depends on this json file that would be incompatible with these servers, I think we ought to add them.

**Comment by radius314** [comment]
Merging

**Comment by radius314** [comment]
The mobile apps do, as well as the Tally.  If they are bombing, I'll roll back.

**Comment by radius314** [comment]
Can you deploy this when you get a chance?

**Comment by LittleGreenViper** [comment]
done
	Chris Marshall
Principal
chris@littlegreenviper.com <mailto:chris@littlegreenviper.com>
https://littlegreenviper.com <https://littlegreenviper.com/>
Little Green Viper Software Development LLC

**Pull request merged**
